# Generated by Django 3.1.7 on 2021-03-17 00:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=250, verbose_name='Тип')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('location', models.CharField(max_length=250, verbose_name='Расположение')),
                ('slug', models.SlugField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
            ],
            options={
                'verbose_name': 'Подстанция',
                'verbose_name_plural': 'Подстанции',
                'ordering': ['city', 'view', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('date', models.DateField(verbose_name='Дата снимка')),
                ('number_photo', models.CharField(max_length=10, verbose_name='Номер снимка')),
                ('view_ru', models.CharField(max_length=15, verbose_name='Тип РУ')),
                ('cell', models.CharField(max_length=15, verbose_name='Узел')),
                ('number_cell', models.CharField(max_length=15, verbose_name='Номер узла')),
                ('element', models.CharField(blank=True, max_length=100, verbose_name='Элемент')),
                ('defect_element', models.CharField(blank=True, max_length=100, verbose_name='Дефектный элемент')),
                ('t0', models.IntegerField(default=0, verbose_name='Темп. OC')),
                ('ta', models.IntegerField(default=0, verbose_name='Темп. фазы - "А"')),
                ('tb', models.IntegerField(default=0, verbose_name='Темп. фазы - "Б"')),
                ('tc', models.IntegerField(default=0, verbose_name='Темп. фазы - "С"')),
                ('result', models.CharField(blank=True, max_length=250, verbose_name='Результат')),
                ('view_defect', models.CharField(blank=True, max_length=50, verbose_name='Вид дефекта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('work_temp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tk.work_temp')),
            ],
            options={
                'verbose_name': 'Снимок',
                'verbose_name_plural': 'Снимки',
                'ordering': ['-date', 'number_photo'],
            },
        ),
    ]
