# Generated by Django 3.1.7 on 2021-03-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substation',
            name='slug',
        ),
    ]
